wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Bird2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurCar1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurCar3.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurCar4.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Board.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Bolt2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Boy.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Car2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Car24.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Coke.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Coupon.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Crossing.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Dancer.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Dancer2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/David2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/David3.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Dog.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Dog1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Doll.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/FaceOcc1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/FaceOcc2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Fish.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/FleetFace.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Football1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Freeman1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Freeman3.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Girl2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Gym.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human5.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human7.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human8.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Jogging.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/KiteSurf.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Lemming.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Man.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Mhyang.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/MountainBike.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Rubik.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Singer1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Skater.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Skater2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Subway.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Suv.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Tiger1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Toy.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Trans.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Twinnings.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Vase.zip
