wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Basketball.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Biker.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Bird1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurBody.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurCar2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurFace.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/BlurOwl.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Bolt.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Box.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Car1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Car4.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/CarDark.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/CarScale.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/ClifBar.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Couple.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Crowds.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/David.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Deer.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Diving.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/DragonBaby.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Dudek.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Football.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Freeman4.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Girl.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human3.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human4.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human6.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Human9.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Ironman.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Jump.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Jumping.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Liquor.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Matrix.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/MotorRolling.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Panda.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/RedTeam.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Shaking.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Singer2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Skating1.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Skating2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Skiing.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Soccer.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Surfer.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Sylvester.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Tiger2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Trellis.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Walking.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Walking2.zip
wget http://cvlab.hanyang.ac.kr/tracker_benchmark/seq/Woman.zip
